# Generated by Django 3.2.2 on 2021-05-10 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Punonjes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emer', models.CharField(max_length=100)),
                ('mbiemer', models.CharField(max_length=100)),
                ('data_e_fillimit', models.DateField()),
                ('data_e_mbarimit', models.DateField(blank=True, default='')),
                ('pozicioni', models.CharField(choices=[('HR', 'HR'), ('Pergjegjes Departamenti', 'Pergjegjes Departamenti'), ('Punonjes Departamenti', 'Punonjes Departamenti')], max_length=100)),
                ('gjinia', models.CharField(choices=[('Femer', 'Femer'), ('Mashkull', 'Mashkull')], max_length=100)),
                ('numri_i_telefonit', models.CharField(max_length=10, null=True)),
                ('statusi', models.CharField(choices=[('Aktiv', 'Aktiv'), ('Joaktiv', 'Joaktiv')], max_length=100)),
                ('username', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
