# Generated by Django 3.2.2 on 2021-05-10 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstpart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulli', models.CharField(choices=[('Financa', 'Financa'), ('Sekretaria', 'Sekretaria'), ('Administrata', 'Administrata'), ('IT', 'IT')], max_length=100)),
                ('Nendepartamenti', models.CharField(max_length=100, null=True, verbose_name=(('Financa', 'Financa'), ('Sekretaria', 'Sekretaria'), ('Administrata', 'Administrata'), ('IT', 'IT')))),
                ('Mbidepartamenti', models.CharField(max_length=100, null=True, verbose_name=(('Financa', 'Financa'), ('Sekretaria', 'Sekretaria'), ('Administrata', 'Administrata'), ('IT', 'IT')))),
                ('pergjegjesi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='firstpart.punonjes')),
            ],
        ),
        migrations.CreateModel(
            name='Departament_per_punonjes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='firstpart.departament')),
                ('punonjes', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='firstpart.punonjes')),
            ],
        ),
    ]
