# Generated by Django 3.2.2 on 2021-05-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpart', '0002_departament_departament_per_punonjes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dite_pushimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pushimet_zyrtare', models.CharField(choices=[('25.12.2021', '25.12.2021'), ('31.12.2021', '31.12.2021'), ('01.06.2021', '01.06.2021')], max_length=100)),
                ('aprovuar', models.BooleanField(default=False)),
            ],
        ),
    ]
